### PR TITLE
Extend script to allow shopware6 as software option

### LINKED ISSUE #7: Add support for Shopware 6
Shopware 6 should be introduced into the array of possible Software `pull` can work with.

### PR DESCRIPTION
**Pull request by juripetersen**
Closes #7

### CODE REVIEW

**Comment by malteriechmann** [comment]
Looks good 👏 

Don't we have to ignore specific database tables when exporting the database?

**Comment by juripetersen** [comment]
Highly depends - in this state we would pull everything.
We could exclude things like users, sales channels and their configs. 
This would lead to a lot of inconsistencies that would have to be handled, so I'm not really sure.

**Review by flemming-pr — APPROVED** [review]

**Comment by malteriechmann** [comment]
@juripetersen Is this still a draft?

**Comment by juripetersen** [comment]
@malteriechmann yes. I still have to come up with a list of certain tables to exclude.

**Comment by juripetersen** [comment]
@malteriechmann I think not excluding tables is actually the best way to go here.
If we exclude users, sales channels etc. we will have a lot of inconsistencies caused by languages and locale.
Thats why I think pulling everything will lead to the most useful solution.

**Pull request merged**
